#pragma once
#ifndef RNNOISE_DATA_H
#define RNNOISE_DATA_H

/* Minimal defines to satisfy rnn.h which expects these from real rnnoise_data.h
   Real file is generated by dump_rnnoise_tables.c and contains model weights.
   For stub build we provide dummy sizes so rnn.h can compile without the full model.
   These defines must be before #include "rnn.h" to break circular include dependency.
*/
#ifndef CONV1_STATE_SIZE
#define CONV1_STATE_SIZE 1
#define CONV2_STATE_SIZE 1
#define GRU1_STATE_SIZE 1
#define GRU2_STATE_SIZE 1
#define GRU3_STATE_SIZE 1
#define CONV1_OUT_SIZE 1
#define CONV2_OUT_SIZE 1
#define GRU1_OUT_SIZE 1
#define GRU2_OUT_SIZE 1
#define GRU3_OUT_SIZE 1
#define CONV1_IN_SIZE 1
#define CONV2_IN_SIZE 1
#define CONV1_STATE_SIZE 1
#endif

/* Additional defines that newer rnn.h might need */
#ifndef ACTIVATION_TANH
#define ACTIVATION_TANH 2
#define ACTIVATION_SIGMOID 1
#endif

/* Forward declarations – needed because rnn.h uses RNNoise and RNNModel
   RNNoise is defined in denoise.c in real build, but for stub we forward declare */
typedef struct RNNoise RNNoise;
typedef struct RNNModel RNNModel;

#include "rnn.h"

/* Provide dummy RNNoise struct if not already defined – real RNNoise is complex model */
#ifndef RNNOISE_DUMMY_DEFINED
#define RNNOISE_DUMMY_DEFINED
struct RNNoise {
    int dummy;
};
#endif

/* Provide dummy RNNState if needed – rnn.h defines it, but for safety */
#ifndef RNNSTATE_DUMMY
#define RNNSTATE_DUMMY 1
#endif

/* Forward declaration – RNNModel is typedef in rnnoise.h, actual struct defined in denoise.c */
extern const RNNModel rnnoise_model_orig;

#endif
